# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 150, 191, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.show_pop_up)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Show Pop up"))
        
    def show_pop_up(self):
          msg= QMessageBox()
          msg.setWindowTitle("Tutorial on PyQt5")
          msg.setText("This is the main text!")
          #4 types of icons in Message box: Warning, critical, information & Question
          #msg.setIcon(QMessageBox.Critical)
          msg.setIcon(QMessageBox.Warning)
          #msg.setIcon(QMessageBox.Information)
          #msg.setIcon(QMessageBox.Question)
         
          #QMessageBox.Ok,QMessageBox.Open,QMessageBox.Save,QMessageBox.Cancel,QMessageBox.Close,QMessageBox.Yes,QMessageBox.No,QMessageBox.Abort,QMessageBox.Retry,QMessageBox.Ignore
          msg.setStandardButtons(QMessageBox.Yes|QMessageBox.No)
          msg.setDefaultButton(QMessageBox.No)

          msg.setInformativeText("Informative text, ya!")
          msg.setDetailedText("details")
          
          msg.buttonClicked.connect(self.popup_button)

          x=msg.exec_()

    def popup_button(self,i):
        print(i.text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
